- name: Configurar SUDO
  hosts: all
  become: yes
  tasks:
    - name: Garantir que o grupo ifpb exista
      ansible.builtin.group:
         name: ifpb
         state: present

    - name: Configurar sudo para o grupo ifpb
      lineinfile:
        path: /etc/sudoers
        regexp: "^%ifpb"
        line: "%ifpb ALL=(ALL) NOPASSWD:ALL"
        state: present

