- name: Configuração do SSH
  hosts: all
  become: yes
  tasks:
    - name: Bloquear acesso root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Permitir autenticação por chave pública
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Limitar acesso SSH ao grupo acesso_ssh
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?AllowGroups"
        line: "AllowGroups acesso_ssh"

    - name: Criar grupo acesso_ssh
      group:
        name: acesso_ssh

    - name: Adicionar usuários ao grupo acesso_ssh
      user:
        name: "{{ item }}"
        groups: acesso_ssh
        append: yes
      loop:
        - Camilly
        - Souza
        - nfs-ifpb  

    - name: Gerar chaves públicas para os usuários
      ansible.builtin.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'keys/' + item + '.pub') }}"
      loop:
        - Camilly
        - Souza
        - nfs-ifpb

