---
- name: Configuração de LVM
  hosts: localhost
  become: yes
  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar o pacote lvm2
      apt:
        name: lvm2
        state: present

    - name: Verificar se os dispositivos estão disponíveis
      stat:
        path: "{{ item }}"
      register: device_status
      with_items:
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
      failed_when: device_status.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Verificar se o grupo de volumes "dados" já existe
      command: vgs --noheadings -o vg_name | grep -w dados
      register: vg_check
      failed_when: false
      changed_when: false

    - name: Criar o grupo de volumes "dados" (se não existir)
      community.general.lvg:
        vg: dados
        pvs:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
      when: vg_check.stdout == ""

    - name: Criar o volume lógico "sistema" no grupo "dados"
      community.general.lvol:
        vg: dados
        lv: sistema
        size: 15G
      register: lv_create_result

    - name: Formatar o volume lógico "sistema" no formato ext4
      filesystem:
        fstype: ext4
        dev: /dev/dados/sistema
      when: lv_create_result is not failed

    - name: Montar o volume lógico "sistema" em /dados
      mount:
        path: /dados
        src: /dev/dados/sistema
        fstype: ext4
        state: mounted
      when: lv_create_result is not failed

    - name: Adicionar a configuração de montagem automática no /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/dados/sistema /dados ext4 defaults 0 0"
        state: present

