---
- name: Criar usuários
  hosts: all
  become: yes
  tasks:
    - name: Garantir que o grupo ifpb exista
      ansible.builtin.group:
        name: ifpb
        state: present

    - name: Criar usuários com senha em texto puro
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        group: ifpb
        shell: /bin/bash
        create_home: yes
        state: present
      loop:
        - { name: "Camilly", password: "camilly" }
        - { name: "Souza", password: "souza" }
        - { name: "nfs-ifpb", password: "ifpb" }
