---
- import_playbook: atualizarSO.yml
- import_playbook: confLVM.yml
- import_playbook: confSUDO.yml
- import_playbook: BannerSSH.yml
- import_playbook: confNFS.yml
- import_playbook: criarUsers.yml
- import_playbook: confHostname.yml
- import_playbook: confSSH.yml
- import_playbook: monitoraAcesso.yml

