---
- name: Configurar script de monitoramento
  hosts: all
  become: yes
  tasks:
    - name: Copiar script de monitoramento para o sistema
      copy:
        dest: /etc/profile.d/monitor.sh
        content: |
          #!/bin/bash
          echo "$(date '+%Y-%m-%d %H:%M'); $USER; $(tty); $(who -u am i | awk '{print $5}')" >> /dados/nfs/acessos
        mode: '0755'

